### ISSUE TITLE
Why setting the GITHUB_TOKEN in the action ?

### ISSUE THREAD

**Issue by rasta-rocket** [tfsec/tfsec-sarif-action#1]
Hey 👋 nice work that you did 💪 
I'm wondering why are you setting the `GITHUB_TOKEN` in the action (not sure it is necessary there)? The `GITHUB_TOKEN` should be used in the next action which is `github/codeql-action/upload-sarif`
🤔 
Thx !!

**Comment by owenrumney** [comment]
Thanks @rasta-rocket  - you're right, it was a bit of laziness assuming nobody was using it.

I've updated the workflow and the readme - the new release is https://github.com/marketplace/actions/run-tfsec-with-sarif-upload

I don't believe the github_token is required to be set for the `upload-sarif` action either, we're using it successfully in https://github.com/tfsec/tfsec-example-project/edit/main/.github/workflows/tfsec.yml without setting it.

Thanks for the feedback!
