### ISSUE TITLE
Allow specification of tfsec version

### ISSUE THREAD

**Issue by mfulgo** [tfsec/tfsec-sarif-action#4]
Right now, the action uses the "latest" release of tfsec in the Dockerfile. Ideally, the user should be able to specify the version of tfsec used during the action's execution. (Running against latest could also allow a supply chain injection attack if tfsec's release is compromised.)

**Comment by owenrumney** [comment]
Thanks @mgulgo - you can now optionally use the `tfsec_version` inpur param to set the version. eg; `v0.42.1`
